### ISSUE TITLE
Add support for graph of event publication/consumption

### ISSUE THREAD

**Issue by charwking** [filso/ng-dependency-graph#8]
Has anyone considered adding support to generate a graph of event flow in an application? (e.g. events published via `$rootScope.$broadcast` and `$rootScope.$emit` and consumed via `$rootScope.$on`)

I haven't thought through all the details to determine how feasible this would be, but I do know it would be a huge help in finding problem spots or complexities in an application's event system.

Thanks!

**Comment by filso** [comment]
Hi, thanks for feedback.
That looks like a very interesting idea, but I doubt whether it's good to implement it here, I think it's out of scope, because:
1. Events are emitted through tree of scopes that might or might not have associated directives / controllers. This is meant to be component graph
2. I doubt whether that's possible on runtime. We could decorate `$emit`, `$on` and `$broadcast` of every scope, but there's no way to find the directive / controller associated with this scope.

You could visualise this through DOM - as it's easy to find a DOM element associated to particular scope. So for example DOM element could flash when it's sending event, and flash in different colour when it's receiving?
